-- Anyone's Guide v0.6
-- Soft-launch primitives: guide visibility, privacy-light analytics, and feedback.
-- Run once after 0001_initial.sql and 0002_private_identity.sql.

-- 1) Visibility ---------------------------------------------------------------
-- Keep is_published for backwards compatibility while making visibility explicit.
-- Add nullable first so this migration is safe to re-run: only rows that have
-- never received a visibility value are backfilled from the legacy boolean.
alter table public.guides
  add column if not exists visibility text;

-- Existing published guides become Unlisted so shared links keep working without
-- unexpectedly adding them to Explore. Existing v0.6 values are left untouched.
update public.guides
set visibility = case when is_published then 'unlisted' else 'draft' end
where visibility is null;

alter table public.guides
  alter column visibility set default 'unlisted',
  alter column visibility set not null;

alter table public.guides
  drop constraint if exists guides_visibility_check;
alter table public.guides
  add constraint guides_visibility_check check (visibility in ('draft', 'unlisted', 'public'));

create or replace function public.sync_guide_publication_state()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.is_published := (new.visibility <> 'draft');
  return new;
end;
$$;

drop trigger if exists guides_sync_publication_state on public.guides;
create trigger guides_sync_publication_state
before insert or update of visibility on public.guides
for each row execute function public.sync_guide_publication_state();

-- Ensure existing rows reflect the new model.
update public.guides
set is_published = (visibility <> 'draft');

-- Public links work for Unlisted and Public. Draft remains owner-only.
drop policy if exists "published or owned guides are readable" on public.guides;
drop policy if exists "visible or owned guides are readable" on public.guides;
create policy "visible or owned guides are readable"
on public.guides for select
using (visibility in ('unlisted', 'public') or auth.uid() = owner_id);

drop policy if exists "visible guide categories are readable" on public.guide_categories;
create policy "visible guide categories are readable"
on public.guide_categories for select
using (
  exists (
    select 1 from public.guides g
    where g.id = guide_id
      and (g.visibility in ('unlisted', 'public') or g.owner_id = auth.uid())
  )
);

drop policy if exists "visible guide places are readable" on public.guide_places;
create policy "visible guide places are readable"
on public.guide_places for select
using (
  exists (
    select 1 from public.guides g
    where g.id = guide_id
      and (g.visibility in ('unlisted', 'public') or g.owner_id = auth.uid())
  )
);

-- 2) Lightweight product analytics -------------------------------------------
-- Intentionally avoids names/emails/IPs in the product table. anonymous_id is a
-- random browser id generated by the client so small-cohort funnel behavior can
-- be understood without requiring a recipient account.
create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  guide_id uuid references public.guides(id) on delete set null,
  anonymous_id text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint app_events_name_check check (event_name in (
    'guide_created',
    'guide_shared',
    'guide_visibility_changed',
    'public_guide_opened',
    'venue_opened',
    'map_opened',
    'maps_handoff',
    'recipient_create_clicked',
    'explore_opened',
    'explore_guide_opened',
    'feedback_submitted'
  ))
);

alter table public.app_events enable row level security;

drop policy if exists "events can be inserted" on public.app_events;
create policy "events can be inserted"
on public.app_events for insert
to anon, authenticated
with check (true);

grant insert on public.app_events to anon, authenticated;
grant usage, select on sequence public.app_events_id_seq to anon, authenticated;

-- No SELECT grant is intentionally given to browser roles. Review analytics in
-- Supabase SQL Editor / dashboard during the soft launch.

-- 3) Feedback ----------------------------------------------------------------
create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null default auth.uid(),
  kind text not null default 'feedback',
  message text not null,
  page_path text,
  created_at timestamptz not null default now(),
  constraint feedback_kind_check check (kind in ('feedback', 'bug', 'report')),
  constraint feedback_message_length check (char_length(message) between 3 and 3000)
);

alter table public.feedback enable row level security;

drop policy if exists "feedback can be submitted" on public.feedback;
create policy "feedback can be submitted"
on public.feedback for insert
to anon, authenticated
with check (user_id is null or user_id = auth.uid());

grant insert on public.feedback to anon, authenticated;

-- Helpful indexes for manual soft-launch analysis.
create index if not exists guides_visibility_updated_idx on public.guides(visibility, updated_at desc);
create index if not exists app_events_created_idx on public.app_events(created_at desc);
create index if not exists app_events_guide_idx on public.app_events(guide_id, created_at desc);
create index if not exists feedback_created_idx on public.feedback(created_at desc);

-- Keep new route names out of editable public handles.
create or replace function public.update_profile_identity(
  p_display_name text,
  p_slug text default null
)
returns public.profiles
language plpgsql
security definer
set search_path = ''
as $$
declare
  user_id uuid := auth.uid();
  current_profile public.profiles%rowtype;
  clean_name text;
  desired_slug text;
  updated_profile public.profiles%rowtype;
begin
  if user_id is null then
    raise exception 'You must be signed in.' using errcode = '42501';
  end if;

  clean_name := trim(coalesce(p_display_name, ''));
  if char_length(clean_name) < 1 then
    raise exception 'Please add the name your friends should see.' using errcode = '22023';
  end if;
  if char_length(clean_name) > 80 then
    raise exception 'Display name must be 80 characters or fewer.' using errcode = '22023';
  end if;

  select * into current_profile from public.profiles where id = user_id;
  if not found then
    raise exception 'Profile not found.' using errcode = 'P0002';
  end if;

  desired_slug := case
    when p_slug is null or trim(p_slug) = '' then current_profile.slug
    else public.normalize_profile_slug(p_slug)
  end;

  if char_length(desired_slug) < 3 or char_length(desired_slug) > 40 then
    raise exception 'Handle must be between 3 and 40 characters.' using errcode = '22023';
  end if;
  if desired_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception 'Use letters, numbers and single hyphens only.' using errcode = '22023';
  end if;
  if desired_slug = any(array['creator','login','edit','preview','explore','feedback','guide','guides','admin','api','auth','settings','account','about','help']) then
    raise exception 'That handle is reserved. Please choose another.' using errcode = '22023';
  end if;

  if desired_slug <> current_profile.slug then
    if exists (select 1 from public.profiles p where p.slug = desired_slug and p.id <> user_id)
      or exists (select 1 from public.profile_aliases a where a.slug = desired_slug and a.profile_id <> user_id) then
      raise exception 'That handle is already taken.' using errcode = '23505';
    end if;

    delete from public.profile_aliases where profile_id = user_id and slug = desired_slug;
    insert into public.profile_aliases (slug, profile_id)
    values (current_profile.slug, user_id)
    on conflict (slug) do nothing;
  end if;

  update public.profiles
  set display_name = clean_name,
      slug = desired_slug,
      onboarding_completed = true
  where id = user_id
  returning * into updated_profile;

  return updated_profile;
end;
$$;

revoke all on function public.update_profile_identity(text, text) from public;
grant execute on function public.update_profile_identity(text, text) to authenticated;
